### ISSUE TITLE
My first issue

### ISSUE THREAD

**Issue by kevin-barre-adeo** [kevin-barre-adeo/scrum-github#1]
# Templates for User Stories & Issues

This document is meant as a template for the **User Stories** and **Issues** created for the project.

Use the corresponding template part whether you want to open a User Story for a new feature to be added later to the project, or for an Issue to report a bug

## User Story Template

When creating a User Story, the following are **mandatory**:
- `Title` section
- Use _[something to be added to the project]_ from the `Title` section part as the **User Story name** in GitHub
- `Acceptance criteria` section

and the following are _optionnal_:
- `Detailed description` section
- `Acceptance criteria` section

### Title

As a **[user]** I want **[something to be added to the project]** (_optionnal_: so that I can **[do something that I could'nt before]**)

### Detailed description

Describe important parts of the user story and its context so developpement team can easily understand what's desired.

### Acceptance criteria

High-level acceptance tests that **must be true from Product owner point of view** to consider the agile user story is complete:
- [ ] Make sure it works with this specific input value
- [ ] The output must include some specific information
- [ ] The process must not write in database if the following error occurs
- [ ] This edge case is taken into account
- [ ] etc.

### Tasks

To be filled by development team **prior to start working on the User Story**.

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
- [ ] ...

### Completion criteria

Developper must check these box to **ensure all technical parts** of the user story have been met
- [ ] Code Complete – as defined by the organization/teams
- [ ] Unit Tested – as defined by the organization/teams
- [ ] Peer Reviewed – as defined by the organization/teams
- [ ] QA Complete – as defined by the organization/teams
- [ ] Documented (As needed; determined by the Scrum Team through tasking at beginning of Sprint)

## Issue Template

TODO

## Ressources
https://www.agilealliance.org/definition-done-user-stories/
https://www.mountaingoatsoftware.com/agile/user-stories
https://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template
